# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build AppView

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for the AppView
      run: dotnet restore
    - name: Build AppView
      run: dotnet build --no-restore
    - name: Restore dependencies for the Gateway
      run: dotnet restore ./PinkSea.Gateway/
    - name: Build Gateway
      run: dotnet build ./PinkSea.Gateway/
